#secrets.toml

# =======================
# AUTENTICACIÓN DASHBOARD
# =======================
[auth.credentials.usernames.dimauser25]
email = "luceroluna582@gmail.com"
name = "DimaUser"
password = "$2b$12$/5M66bEy3F0MUykkuCiqW.0N79MUks7hwhdmEDv5qrRaQcsIrJaMS"

[auth.cookie]
expiry_days = 7
key = "0IppJeBduXTaQhiA4BYRHt85ZyoNuDcymvCiu-ycv2o"
name = "dima_dashboard_cookie"

[auth.preauthorized]
emails = ["luceroluna582@gmail.com"]

# =======================
# API LEGACY (fecha actualización)
# =======================
[api]
API_BASE = "https://fastapi-api-454780168370.us-central1.run.app"
API_TOKEN = "Apocositumuydetective007"

# =======================
# API NUEVA COMPRAS / VENTAS
# =======================

API_BASE_COMPRAS_API = "https://compras-api-454780168370.us-central1.run.app"
API_TOKEN_COMPRAS_API = "super_token_largo_y_secreto_para_que_no_me_vayan_a_metER_ALLL_BOTE_OALANEXO_vdd_84659763256546696446_MICKEY_EL_MEJOR_PERRO_DEL_MUNDO_SI_SE_PIERDE_LLORO_0838377211891738281"
